Repository pattern applied for the persistence layer using Realm
eduardb/ClujBike pull request #4
Opened 2017-01-07 23:36 UTC by RoxanaTanaselea

I implemented the repository pattern for the persistence layer using Realm.
I followed the steps presented in the #2, but with Realm.

2017-01-08 20:20 UTC, eduardb requested changes
Just a small blocker, and a few small comments, but otherwise a great job.

2017-01-08 20:20 UTC, eduardb commented on app/src/main/java/com/deveddy/clujbike/data/repository/models/StationRealm.java
> +        isValid = isValid;
Ruh-roh, you have a `this.` missing 🙀

2017-01-08 20:20 UTC, eduardb commented on app/src/main/java/com/deveddy/clujbike/data/repository/StationRealmRepository.java
> +    private final RealmProvider realmProvider;
Could you insert a blank line here for better readability, please?

2017-01-08 20:20 UTC, eduardb commented on app/src/main/java/com/deveddy/clujbike/data/repository/StationRealmRepository.java
> +    private final Mapper<StationEntity, StationRealm> toRealmMapper;
Who is `toRealm`? `entityToRealm` would probably be a better name.

2017-01-08 20:20 UTC, eduardb commented on app/src/main/java/com/deveddy/clujbike/data/repository/StationRealmRepository.java
> +    private final Mapper<StationRealm, StationEntity> toEntityMapper;
Same here

2017-01-08 20:20 UTC, eduardb commented on app/src/main/java/com/deveddy/clujbike/data/repository/mapper/station/StationEntityRealmMapper.java
> +public class StationEntityRealmMapper implements Mapper<StationEntity, StationRealm> {
`StationEntityToRealmMapper` would be a bit better, don't you think?

2017-01-08 20:20 UTC, eduardb commented on app/src/main/java/com/deveddy/clujbike/data/repository/mapper/station/StationRealmEntityMapper.java
> +        return StationEntity.builder()
👍

2017-01-08 20:20 UTC, eduardb commented on app/src/main/java/com/deveddy/clujbike/data/repository/specifications/RealmSpecification.java
> +public interface RealmSpecification extends Specification {
Maybe would be worth it generifying this interface so it can be used in the future for other types as well, not only `StationRealm`

2017-01-08 20:20 UTC, eduardb commented on app/src/test/java/com/deveddy/clujbike/data/repository/mapper/station/StationEntityRealmMapperTest.java
> +        StationRealm stationRealm;
Please inline this variable

2017-01-08 20:20 UTC, eduardb commented on app/src/test/java/com/deveddy/clujbike/data/repository/mapper/station/StationRealmEntityMapperTest.java
> +    StationRealmEntityMapper sut;
Blank line? :D

2017-01-08 20:20 UTC, eduardb commented on build.gradle
> +        classpath "io.realm:realm-gradle-plugin:2.3.0-SNAPSHOT"
😟 We shouldn't be using snapshots. As soon as 2.3.0 hits stable, we should take care of this.

2017-01-08 20:20 UTC, eduardb commented on app/src/main/java/com/deveddy/clujbike/data/repository/models/StationRealm.java
> +    public void setValid(boolean isValid) {
Shouldn't this method's name be `setStationValid()` for symmetry with the getter?

2017-01-08 20:57 UTC, RoxanaTanaselea commented on app/src/main/java/com/deveddy/clujbike/data/repository/models/StationRealm.java
> +    public void setValid(boolean isValid) {
valid point

2017-01-10 20:22 UTC, eduardb approved these changes

2017-01-10 20:22 UTC, merged